### ISSUE TITLE
Add mock-onionify

### ISSUE THREAD

**Issue by jvanbruegge** [staltz/cycle-onionify#52]
It would be helpful, if you could inject an initial state into onionify.
So basicly:
```ts
onionify(main, { count: 40 })(sources);
```
This would make testing with default reducers using prevState easier

**Comment by staltz** [comment]
I understand the purpose for testing, but I'm cautious about adding that API, it seems people could use it to provide initial state as application logic.

How about just passing a StateSource to main?

```js
main({ ...sources, onion: new StateSource(xs.of({count: 40})) })
```

**Comment by jvanbruegge** [comment]
the state source wont update that way, will it?

**Comment by staltz** [comment]
It won't, just like the DOM doesn't update when you use mockDOMSource to give a fake DOMSource. To test, you inspect whether the output (the reducers) looks correct. But since state management is not effects, you could test an application that was onionified, right? Another approach is to wrap the `main` in a larger component which initializes state with a default reducer.

**Comment by jvanbruegge** [comment]
> you could test an application that was onionified, right? 

Yes

> Another approach is to wrap the main in a larger component which initializes state with a default reducer.

That's what I'm doing ATM, I think you are right, a simple helper for `cyclejs-test-helpers` will do the job just fine.
