### ISSUE TITLE
pickMerge seems to swallow events

### ISSUE THREAD

**Issue by jvanbruegge** [staltz/cycle-onionify#59]
Not entirely sure why, but I have a reproducing case:
[Live demo at webpackbin](https://www.webpackbin.com/bins/-KziAuYfyHJw2JPzu74B)

**Expected behavior:**
App logs events on button click

**Actual behavior:**
Nothing happens

```js
import xs from 'xstream';
import { run } from '@cycle/run';
import { div, button, makeDOMDriver } from '@cycle/dom';
import onionify, { makeCollection } from 'cycle-onionify';

function Item(sources) {
  //works
  /*sources.DOM.select('.tab').events('click')
    .addListener({ next: console.log });*/
  
  return {
    DOM: xs.of(div([button('.tab', {}, ['Test'])])),
    log: sources.DOM.select('.tab').events('click')
  }
}

const List = makeCollection({
  item: Item,
  itemKey: x => x.id, // does not matter
  itemScope: x => '._' + x, // does not matter
  collectSinks: instances => ({
    DOM: instances.pickCombine('DOM').map(div),
    log: instances.pickMerge('log')
  })
});

function Parent(sources) {
  const sinks = List(sources);
  
  return {
    ...sinks,
    onion: xs.of(() => [{ id: 0 }, { id: 1 }, { id: 2 }])
  };
}

run(onionify(Parent), {
  DOM: makeDOMDriver('#app'),
  log: sink$ => {
    sink$.addListener({
      next: console.log
    })
  }
});
```

**Comment by staltz** [comment]
I finally debugged this. The problem is `xs.of(() => [...])` is the only reducer stream in the application, and it completes synchronously. When that happens, `sources.onion.state$` will also complete, and `pickMerge` is built to complete when the state$ completes. Actually so does `pickCombine`, but it doesn't matter because the combine happens early enough to get all of the three divs.

Not sure what the solution be. One question is: in what cases is it useful to have `complete` on `pickCombine` and `pickMerge`?

**Comment by staltz** [comment]
Okay, actually Cycle run does not replicate `complete` events from sinks, but `imitate` inside onionify does https://github.com/staltz/cycle-onionify/blob/1b6c05ab0e11907fa70b7570bb994e0c51500de4/src/onionify.ts#L46 (because this is not a driver).

So I think a good solution for now is avoiding `complete` when onionify imitates reducer$.

**Comment by jvanbruegge** [comment]
> Also, a general question that applies for everything in cycle.js: do we want source streams to complete at all? To me, it seems safe to assume that all sources and all sinks are never-completing, but intermediate streams in between are allowed to complete for the sake of concatenation.

I agree with that. The external world should never complete

**Comment by staltz** [comment]
Version 5.0.0 released. Could you see if it works for you?

**Comment by jvanbruegge** [comment]
I can try, but the issue i am having is a different one. I just discovered this when trying to reproduce my issue.
I have the problem that an collection works as expected if i use total DOM isolation and stops receiving events once i use sibling isolation
I debugged a bit, and it looks like the issue is because the dom driver attaches additional css classes that somehow arent present in the final dom

**Comment by staltz** [comment]
Well, at least the issue reported originally was fixed. We can open other issues for the other stuff
